# Generated by Django 4.0.5 on 2022-07-15 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tip', '0004_remove_bettingtip_country_betpawatip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='betpawatip',
            old_name='title',
            new_name='booking_code',
        ),
    ]
